package xyz.darkcomet.cogwheel.framework.primitives

enum class ImageAliasType {
    CUSTOM_EMOJI,
    GUILD_ICON,
    GUILD_SPLASH,
    GUILD_DISCOVERY_SPLASH,
    GUILD_BANNER,
    USER_BANNER,
    DEFAULT_USER_AVATAR,
    USER_AVATAR,
    GUILD_MEMBER_AVATAR,
    AVATAR_DECORATION,
    APPLICATION_ICON,
    APPLICATION_COVER,
    APPLICATION_ASSET,
    ACHIEVEMENT_ICON,
    STORE_PAGE_ASSET,
    STICKER_PACK_BANNER,
    TEAM_ICON,
    STICKER,
    ROLE_ICON,
    GUILD_SCHEDULED_EVENT_COVER,
    GUILD_MEMBER_BANNER,
    GUILD_TAG_BADGE
}